name: UpdateResumeImage

on:
  push:
    paths:
      - "resume.tex"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          
      - name: LaTeX PDF Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
          
      - name: Update PDF in Repository
        uses: test-room-7/action-update-file@v1
        with:
            file-path: resume.pdf
            commit-msg: CI/CD Pipeline - Updated PDF
            github-token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Install ImageMagick
        run: sudo apt-get install imagemagick
        
      - name: Allow PDF-PNG Conversion
        run: |
              sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
              sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
            
      - name: Update Resume Image 
        run: convert -verbose -density 300 -trim -background white -alpha remove -alpha off resume.pdf -quality 100 resume.png
          
      - name: Update Image Preview in Repository
        uses: test-room-7/action-update-file@v1
        with:
            file-path: resume.png
            commit-msg: CI/CD Pipeline - Updated Resume Image
            github-token: ${{ secrets.GITHUB_TOKEN }}
