name: Update Resume PDF & Image

on:
  push:
    paths:
      - "resume.tex"
      - ".github/workflows/main.yml"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build_resources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
          
      - name: LaTeX PDF Compilation
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
            
      - name: Install ImageMagick & GhostScript
        run: |
              sudo apt-get install imagemagick
              sudo apt-get install ghostscript
        
      - name: Allow PDF-PNG Conversion
        run: |
              sudo sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
              sudo sed -i_bak 's/rights="none" pattern="PDF"/rights="read | write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
            
      - name: Update Resume Image 
        run: convert -verbose -density 500 -background white -alpha remove -alpha off resume.pdf -quality 100 resume.png
        
      - name: Save Resume Resources
        uses: actions/upload-artifact@v2
        with:
          name: resume_resources
          path: ./[resume]*
      
  update_repository:
    runs-on: ubuntu-latest
    needs: build_resources
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources
    
      - name: Update Image Preview in Repository
        uses: test-room-7/action-update-file@v1
        with:
            file-path: resume.png
            commit-msg: CI/CD Pipeline - Updated Resume Image
            github-token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Update PDF in Repository
        uses: test-room-7/action-update-file@v1
        with:
            file-path: resume.pdf
            commit-msg: CI/CD Pipeline - Updated Resume PDF
            github-token: ${{ secrets.GITHUB_TOKEN }}

  update_personal_website:
    runs-on: ubuntu-latest
    needs: build_resources
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          name: resume_resources
    
      - name: Pushing PDF to Website Repositoryy
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'resume.pdf'
          destination_repo: 'thienlongtran/thienlongtran.github.io'
          destination_folder: 'assets'
          user_email: 'tltran5@uno.edu'
          user_name: 'thienlongtran'
